---
apiVersion: v2
name: vh-notification-api
home: https://github.com/hmcts/vh-notification-api
version: 0.0.16
description: Helm Chart for VH Notification API
maintainers:
  - name: VH Devops

dependencies:
  - name: java
    version: 5.3.0
    repository: oci://hmctspublic.azurecr.io/helm
