---
apiVersion: v2
name: vh-notification-api
home: https://github.com/hmcts/vh-notification-api
version: 0.0.15
description: Helm Chart for VH Notification API
maintainers:
  - name: VH Devops

dependencies:
  - name: java
    version: 3.8.0
    repository: https://hmctspublic.azurecr.io/helm/v1/repo/
