---
java:
  aadIdentityName: vh-aad-identity
  applicationPort: 8080
  image: "sdshmctspublic.azurecr.io/vh/notification-api:latest"
  ingressHost: vh-notification-api.{{ .Values.global.environment }}.platform.hmcts.net
  livenessPath: /healthcheck/liveness
  livenessDelay: 360
  livenessPeriod: 120
  livenessTimeout: 3
  livenessFailureThreshold: 3
  readinessPath: /healthcheck/readiness
  readinessDelay: 360
  readinessPeriod: 120
  readinessTimeout: 3
  startupPath: /healthcheck/startup
  startupDelay: 360
  startupPeriod: 120
  startupFailureThreshold: 20
  startupTimeout: 3
  releaseNameOverride: vh-notification-api
  replicas: 2
  keyVaults:
    vh-infra-core:
      excludeEnvironmentSuffix: false
      resourceGroup: vh-infra-core-{{ .Values.global.environment }}
      usePodIdentity: true
      secrets:
        - name: connectionstrings--applicationinsights
          alias: applicationinsights--connectionstring
        - azuread--tenantid
        - connectionstrings--vhnotificationsapi
    vh-notification-api:
      excludeEnvironmentSuffix: false
      resourceGroup: vh-infra-core-{{ .Values.global.environment }}
      usePodIdentity: true
      secrets:
        - azuread--clientid
        - azuread--clientsecret
        - notifyconfiguration--apikey
        - notifyconfiguration--callbacksecret
        - name: azuread--identifieruri
          alias: services--vhnotificationapiresourceid
        - name: azuread--identifieruri
          alias: azuread--vhnotificationapiresourceid
        - name: launchdarkly--sdkkey
          alias: FeatureToggle--SdkKey
  environment:
    ASPNETCORE_URLS: http://+:8080
    DISABLEHTTPSREDIRECTION: true
    Logging__LogLevel__Default: debug
    Logging__LogLevel__Microsoft: debug
    Logging__LogLevel__System: debug
    NotifyConfiguration__Environment: "{{ lower .Values.global.environment }}"
